name: Build Mini Globed Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Android32", target: "Android32", os: ubuntu-latest }
          - { name: "Android64", target: "Android64", os: ubuntu-latest }

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK 26
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Lock mod.json to prevent auto-update
        run: |
          echo "Before:"
          cat mod.json
          chmod 444 mod.json

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
          sdk: v4.6.0
          cli: v3.4.0
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Restore mod.json permissions
        if: always()
        run: chmod 644 mod.json

  package:
    name: Package mod
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Combine .geode files
        uses: geode-sdk/build-geode-mod/combine@main

      - name: Upload final .geode
        uses: actions/upload-artifact@v4
        with:
          name: mini-globed-android
          path: "*.geode"